### ISSUE TITLE
Keyboard Handler

### ISSUE THREAD

**Issue by MyZik** [php-telegram-bot/core#434] opened 2017-03-16 17:47 UTC
### Required Information

- PHP version: 5.6.3
- PHP Telegram Bot version: last
- Using MySQL database: no
- Update Method: Webhook
- Self-signed certificate: yes

### Expected behaviour
The bot response to the response in the button

### Actual behaviour
I have a /keyboard command that prints out the buttons. How do I make a message when I select button "1"? When I run /keyboard I choose "1" but bot does't respond me

### Extra details
```
class KeyboardCommand extends UserCommand
{
    protected $name = 'keyboard';
    protected $description = 'Show a custom keyboard with reply markup';
    protected $usage = '/keyboard';
    protected $version = '0.2.0';

    public function execute()
    {
        $chat_id = $this->getMessage()->getChat()->getId();
        $text = 'Hi!' . PHP_EOL . ' Choose button';
        
        $message = $this->getMessage();
        $choice = trim($message->getText());
        
        switch($choice)
        {
            case '1':
                $data = [
                    'chat_id'      => $chat_id,
                    'text'         => 'OK!',
                ];
                break;
                
            default:
                $keyboards = [];
                $keyboards[] = new Keyboard(
                    ['1', 'oranges'],
                    ['bananas', 'watermelons'],
                    ['vegetables']
                );
               
                $keyboard = $keyboards[0]
                    ->setResizeKeyboard(true)
                    ->setOneTimeKeyboard(true)
                    ->setSelective(false);

                $data = [
                        'chat_id'      => $chat_id,
                        'text'         => $text . $choice,
                        'reply_markup' => $keyboard,
                    ];
                    
                break;
        }
        
        return Request::sendMessage($data);
    }
}
```

**Comment by jacklul** [comment] 2017-03-16 18:21
Use the `Conversation` feature to redirect user input to your command.

somewhere before `switch()`:
```php
$conversation = new Conversation($user_id, $chat_id, $this->getName());
```
(`$user_id` and `$chat_id` must already be declared and contain appropriate values)

Once the command is done (no more user input needed) don't forget to 

```php
$conversation->stop();
```

otherwise all user input will keep getting redirected to this command.

**Comment by MyZik** [comment] 2017-03-17 07:56
@jacklul Thanks for your answer. I tried to change for myself, but it did not work out. I want information to be displayed after pressing a button, and then the dialogue stopped. I do not know what these variables are $notes, $state. How can I make this easier? When I send 1, the bot asks my age. And I must end the dialogue and display the information that I chose 1

```
class KeyboardCommand extends UserCommand
{
    /**#@+
     * {@inheritdoc}
     */
    protected $name = 'keyboard';
    protected $description = 'Show a custom keyboard with reply markup';
    protected $usage = '/keyboard';
    protected $version = '0.2.0';
    protected $need_mysql = true;
    protected $conversation;
    /**#@-*/
    /**
     * {@inheritdoc}
     */
     
    public function execute()
    {
        $message = $this->getMessage();
        $chat = $message->getChat();
        $user = $message->getFrom();
        $text = trim($message->getText(true));
        $chat_id = $chat->getId();
        $user_id = $user->getId();
        
        $data = [
            'chat_id' => $chat_id,
        ];
        if ($chat->isGroupChat() || $chat->isSuperGroup()) {
            $data['reply_markup'] = Keyboard::forceReply(['selective' => true]);
        }
        
        //Conversation start
        $this->conversation = new Conversation($user_id, $chat_id, $this->getName());
        $notes = &$this->conversation->notes;
        !is_array($notes) && $notes = [];
        //cache data from the tracking session if any
        $state = 0;
        if (isset($notes['state'])) {
            $state = $notes['state'];
        }
        $result = Request::emptyResponse();

        switch ($state) {
            case 0:
                if ($text === '') {
                    $notes['state'] = 0;
                    $this->conversation->update();
                    $data['text']         = 'Выберите интересующий Вас раздел';
                    
                    $keyboards = [];
                    $keyboards[] = new Keyboard(
                     ['1', 'oranges'],
                     ['bananas', 'watermelons'],
                     ['vegetables']
                 );
                   
                    $keyboard = $keyboards[0]
                        ->setResizeKeyboard(true)
                        ->setOneTimeKeyboard(true)
                        ->setSelective(false);
                    
                    $data['reply_markup'] = $keyboard;
                    $result = Request::sendMessage($data);
                    break;
                }
                $notes['name'] = $text;
                $text          = '';
            // no break
            case 1:
                if ($text === '1') {
                    $notes['state'] = 1;
                    // $this->conversation->update();
                    $this->conversation->stop();
                    $data['text'] = 'Your choice: 1';
                    $data['reply_markup'] = Keyboard::remove(['selective' => true]);
                    $result = Request::sendMessage($data);
                    break;
                 }
                }

                $notes['surname'] = $text;
                $text             = '';
            // no break
            case 2:
                if ($text === '' || !is_numeric($text)) {
                    $notes['state'] = 2;
                    $this->conversation->update();
                    $data['text'] = 'Type your age:';
                    if ($text !== '') {
                        $data['text'] = 'Type your age, must be a number:';
                    }
                    $result = Request::sendMessage($data);
                    break;
                }
                $notes['age'] = $text;
                $text         = '';
            // no break
            case 3:
                if ($text === '' || !in_array($text, ['M', 'F'], true)) {
                    $notes['state'] = 3;
                    $this->conversation->update();
                    $data['reply_markup'] = (new Keyboard(['M', 'F']))
                        ->setResizeKeyboard(true)
                        ->setOneTimeKeyboard(true)
                        ->setSelective(true);
                    $data['text'] = 'Select your gender:';
                    if ($text !== '') {
                        $data['text'] = 'Select your gender, choose a keyboard option:';
                    }
                    $result = Request::sendMessage($data);
                    break;
                }
                $notes['gender'] = $text;
            // no break
            case 4:
                if ($message->getLocation() === null) {
                    $notes['state'] = 4;
                    $this->conversation->update();
                    $data['reply_markup'] = (new Keyboard(
                        (new KeyboardButton('Share Location'))->setRequestLocation(true)
                    ))
                        ->setOneTimeKeyboard(true)
                        ->setResizeKeyboard(true)
                        ->setSelective(true);
                    $data['text'] = 'Share your location:';
                    $result = Request::sendMessage($data);
                    break;
                }
                $notes['longitude'] = $message->getLocation()->getLongitude();
                $notes['latitude']  = $message->getLocation()->getLatitude();
            // no break
            case 5:
                if ($message->getPhoto() === null) {
                    $notes['state'] = 5;
                    $this->conversation->update();
                    $data['text'] = 'Insert your picture:';
                    $result = Request::sendMessage($data);
                    break;
                }
                /** @var PhotoSize $photo */
                $photo             = $message->getPhoto()[0];
                $notes['photo_id'] = $photo->getFileId();
            // no break
            case 6:
                if ($message->getContact() === null) {
                    $notes['state'] = 6;
                    $this->conversation->update();
                    $data['reply_markup'] = (new Keyboard(
                        (new KeyboardButton('Share Contact'))->setRequestContact(true)
                    ))
                        ->setOneTimeKeyboard(true)
                        ->setResizeKeyboard(true)
                        ->setSelective(true);
                    $data['text'] = 'Share your contact information:';
                    $result = Request::sendMessage($data);
                    break;
                }
                $notes['phone_number'] = $message->getContact()->getPhoneNumber();
            // no break
            case 7:
                $this->conversation->update();
                $out_text = '/Survey result:' . PHP_EOL;
                unset($notes['state']);
                foreach ($notes as $k => $v) {
                    $out_text .= PHP_EOL . ucfirst($k) . ': ' . $v;
                }
                $data['photo']        = $notes['photo_id'];
                $data['reply_markup'] = Keyboard::remove(['selective' => true]);
                $data['caption']      = $out_text;
                $this->conversation->stop();
                $result = Request::sendPhoto($data);
                break;
        }
        return $result;
    }
}

```

**Comment by jacklul** [comment] 2017-03-17 09:15
I don't know now what you're trying to achieve, you copied whole survey command into your own, you don't need state and notes variables in what you want to do, I told you what to do in my previous message, all you had to do is to initalize Conversation in your command so all input will be handled by it, then you close it when you no longer want all input to be redirected to that command. 

Survey command is just general example of the usage of this feature, it's for testing and looking at code to see what each line does.

**Comment by chuv1** [comment] 2017-04-02 10:30
Still need any help? Могу быстро объяснить по-русски.

**Comment by iligzar** [comment] 2017-05-09 15:09
Будь добр, распиши как обрабатывать выбор кнопок и вообще как обрабатывать сообщения (не команды) приходящие от пользователя.

**Comment by noplanman** [comment] 2017-05-09 15:18
@iligzar Would be great if you could keep it in English, otherwise we can't help 😕

**Comment by iligzar** [comment] 2017-05-09 16:00
noplanman, of course. chuv1 written that can help in  russian.
so..
I dont understand how to work handler (webhook) with user messages (not command) and chose keybord button. 
Example: Bot after start comand send to user answer "How are you?", user ask "fine" or "bad", bot hanle this answer and sendmessage to user "Great!" or "not great!".

please write 2 simple example how to do this with keybord and plantext.

P.S. sorry for my english

**Comment by arkhub** [comment] 2017-08-24 01:08
sorry to add, I also have similar problem like I want to create menu from keyboard. and the problem is 
what I want : when i press "menu 01" in keyboard, i want it to redirect to "/menu01" and after searching the web it's somewhat impossible in telegram (label and text must be the same).

is there any workaround for this? I've been thinking like
1. alias for command, like "/help" can be called to if user type "helpme" (without "/")
2. custom command that can be called without "/"

but I haven't find out how to do it in here.

**Comment by noplanman** [comment] 2017-08-24 20:15
@arkhub Have a look here:
https://github.com/php-telegram-bot/core/issues/485#issuecomment-298847941

**Comment by arkhub** [comment] 2017-08-24 22:11
thanks it works perfectly :)

**Comment by MyZik** [comment] 2017-08-25 10:44
@noplanman yeap, thanks

**Closed** 2017-08-25 11:16 UTC
