### ISSUE TITLE
Call to a member function isOk() on null

### ISSUE THREAD

**Issue by khaninejad** [php-telegram-bot/core#263] opened 2016-08-02 11:12 UTC
PHP Fatal error:  Call to a member function isOk() on null in /home/xxx/public_html/telegram/vendor/longman/telegram-bot/src/Telegram.php on line 340

**Comment by noplanman** [comment] 2016-08-02 12:26
Hi!
Could you please provide some more details as to when this error occurs?
Also, do you have the raw update?

If not, you can activate the logging and then execute the command again. That should add the raw update entry to the log.

**Comment by jacklul** [comment] 2016-08-02 15:10
Happens in my bots from time to time too, usually it means execute() didn't return anything or returned bool value (?), I believe it expects result from Request to Telegram API.

**Comment by khaninejad** [comment] 2016-08-03 04:39
@noplanman I can't trace the locationof the error. just bot stop working and this error appeared.

**Comment by noplanman** [comment] 2016-08-03 09:59
Does this happen with any command?

Also, could you try to use the [getUpdate](https://github.com/akalongman/php-telegram-bot/blob/master/README.md#getupdate-installation) method to make sure that it's not the webhook that might be causing this?

**Comment by nickustinov** [comment] 2016-08-03 10:24
Same issue, this only happens in handle(). Temporarily had to:

        $this->processUpdate(new Update($post, $this->bot_name));
        return true;

Nick

**Comment by noplanman** [comment] 2016-08-03 12:21
@nickustinov Do you maybe have any more details for us to debug this?
Raw update or an error log?

**Comment by noplanman** [comment] 2016-08-03 12:59
@khaninejad @nickustinov 
Are you experiencing this issue with custom commands?
Do the default commands work? (e.g. `/echo Hello World`)

**Comment by nickustinov** [comment] 2016-08-03 16:29
@noplanman Actually, it seems Telegram is sending POSTs repeatedly without user entering anything, that produces the error mentioned above. Here is what it keeps sending in my case so irt goes to $this->input in handle() (update_id is chaning all the time)

"{\"update_id\":338210771,\n\"message\":{\"message_id\":3616,\"from\":{\"id\":myid,\"first_name\":\"Nick\",\"last_name\":\"Ustinov\"},\"chat\":{\"id\":myd,\"first_name\":\"Nick\",\"last_name\":\"Ustinov\",\"type\":\"private\"},\"date\":1470240889,\"text\":\"\\u0416\\u0443\\u0440\\u043d\\u0430\\u043b\"}}"

Hope this helps.

**Comment by nickustinov** [comment] 2016-08-03 16:31
i've replaced my id in previous message with "myid", it was numeric and proper.

**Comment by khaninejad** [comment] 2016-08-03 17:05
Yes, sometimes when some command has an error then this error return on
every command execution.
I think this is related to null response, bot limits or commend handshake.

**Comment by khaninejad** [comment] 2016-08-04 04:36
+1

**Comment by noplanman** [comment] 2016-08-04 12:17
> Actually, it seems Telegram is sending POSTs repeatedly without user entering anything

Very strange. I'd suggest you get a new token from BotFather for your bot (just send `/token` to BotFather) and also change the hook URL. You shouldn't be getting messages like that if nobody is interacting with the bot.

@khaninejad Yes, the return value from the command needs to be a ServerResponse object, nothing else. So if a custom command returns `null`, then this error will occur. If you need to return an empty response, you can use `return Request::emptyResponse();`

**Comment by MBoretto** [comment] 2016-08-04 17:36
This happen to me when the telegram server is down. If you open the page
with the browser you get: 'error Nigix black bla' hope that helps

**Comment by khaninejad** [comment] 2016-08-04 17:43
But i cant track which command cause this error.

**Comment by khaninejad** [comment] 2016-08-13 09:02
Still getting this error.
Its prevent my users to start my bot.
any update?

**Comment by noplanman** [comment] 2016-08-13 09:26
Please try what @nickustinov suggested [here](https://github.com/akalongman/php-telegram-bot/issues/263#issuecomment-237200633) until this is fixed in master.

This error shouldn't be happening though, so something is up...

**Comment by nickustinov** [comment] 2016-08-13 09:45
Commenting on this, I have tried with different bot token etc - no change, the issue is still there. I have noticed it keeps sending update POST of users last input, which is in fact GenericMessage and executes certain command from genericmessage php, however it seems telegram does not ack the POST was received and keeps bombing. Sort of;)

**Comment by noplanman** [comment] 2016-08-13 14:58
You using Webhook or GetUpdates?
With or without database?

**Comment by khaninejad** [comment] 2016-08-13 15:00
Webhook with database.

**Comment by nickustinov** [comment] 2016-08-13 15:15
Webhook with database too.

**Comment by MBoretto** [comment] 2016-08-14 13:22
Please enable raw log and report the update. Do you use inlinekeyboards?

**Comment by khaninejad** [comment] 2016-08-14 18:39
Yes I do.

**Comment by MBoretto** [comment] 2016-08-14 20:43
You need to check that button with url are valid link otherwise telegram stop you bot.
Also callback data can't exeed the 64 limits.

**Comment by khaninejad** [comment] 2016-08-15 04:46
It's is just one URL without callback.

**Comment by noplanman** [comment] 2017-04-26 19:45
@khaninejad I just realised this issue is still open.

Have you managed to resolve the problem in the meantime?

**Comment by khaninejad** [comment] 2017-04-27 04:30
@noplanman no

**Comment by noplanman** [comment] 2017-04-27 09:03
Could you please open a new issue with your situation as it is now with some code examples for us to work with?
Otherwise it's super difficult to figure out what's going on 😕

**Comment by jacklul** [comment] 2017-04-27 09:07
The only time I had this is when I didn't notice my command in rare cases didn't return anything or returned true/false instead of Request result.

**Closed** 2018-01-12 18:09 UTC
