### ISSUE TITLE
Conflict  with autoload, when  command don't exist  

### ISSUE THREAD

**Issue by dhayzon** [php-telegram-bot/core#1196] opened 2021-03-27 22:59 UTC
### 🐞 Bug Report

<--
❗ NEVER put your Telegram API key or any other private details here. (like passwords, user IDs, etc.)
Substitute them like <API_KEY> or <USER_ID> etc.
-->

#### Required Information

|  ?                        |  !
| ---                       | ---
| Operating system          | Name and version
| PHP Telegram Bot version  |- Version 0.71.0 
| PHP version               | 7.3
| MySQL version             |   none
| Update Method             | Webhook / 
| Self-signed certificate   | yes  
| RAW update (if available) | `{...}`

#### Summary

when user put random command  command
example

/skdlsdk
 
`if (class_exists($command_class))`

pass true if you have autoload and **skdlsdkcommand** not found error and bot not working

 
file  \longman\telegram-bot\src\Telegram.php

in   public function getCommandObject(string $command, string $filepath = ''): ?Command

I recommend    pass false value  in class_exists($command_class, false) condition 

https://www.php.net/manual/es/function.class-exists.php

**Comment by noplanman** [comment] 2021-03-30 16:46
Hi @dhayzon, thanks for reporting an issue.

I don't fully understand what the problem is. If I try to send a command that doesn't exist, `GenericCommand.php` gets executed, which is correct behaviour.

What error do you get when trying to execute your random command `/skdlsdk`?

**Comment by noplanman** [comment] 2021-05-01 12:49
Closing off as I can't reproduce this.

Please reopen with a more detailed explanation if need be, thanks!

**Closed by noplanman** 2021-05-01 12:49 UTC
Labels: bug
